### ISSUE TITLE
Project not go-gettable

### ISSUE THREAD

**Issue by i4ki** [NeowayLabs/cloud-machine#10]
Project has 2 programs in the main package. This isn't the go way to package binaries because it's not go-gettable.
When the project has several binaries, it commonly have a `cmd` directory to them.
Eg.:

```
cloud-machine/cmd/cluster-up/main.go
cloud-machine/cmd/machine-up/main.go
```

**Comment by katcipis** [comment]
Makes sense for me

**Comment by guilherme-santos** [comment]
Great, to be honest I haven't seen any project that create more than one binary.. Put inside of cmd folder seems to be ok!
