### ISSUE TITLE
Add support to tags

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/cloud-machine#4]
It would be cool to have a way to add N tags on the machine creation automation (not only the name).

**Comment by lborguetti** [comment]
@katcipis do you have any idea how to make this feature?

**Comment by katcipis** [comment]
Never looked at cloud machine code yet, talking with @guilherme-santos it seems very feasible. Sadly im not in great of need for it right now, that's why I'm not putting too much effort on it :-)

**Comment by lborguetti** [comment]
@katcipis Sorry, but my question is about user interaction :-)

**Comment by guilherme-santos** [comment]
Actually I took a look on it, and the problem is that my yml library don't accept dynamic fields, we should use something like:

```
- {key: "Env", value: "Prod"}
- {key: "Debug", value: false}
```

I think it's ok, right?

**Comment by guilherme-santos** [comment]
@lborguetti the tags should be add inside of yml, I'm not sure if inside of machine or cloud file

**Comment by lborguetti** [comment]
@guilherme-santos I think its better inside of machine file ;)

**Comment by katcipis** [comment]
I agree on the machine file
