### ISSUE TITLE
[machine-up] Error: The request must contain the parameter zone

### ISSUE THREAD

**Issue by katcipis** [NeowayLabs/cloud-machine#7]
Cant build machines right now, with the same config files that used to work:

```
/home/katz/workspace/go/src/github.com/NeowayLabs/cloud-machine/machine-up ./envs/staging/cloud-machine/k8s-node.yml
Creating new volume...
--------- NEW VOLUME ---------
[FATAL] Error getting machine: The request must contain the parameter zone (MissingParameter)
```

**Comment by katcipis** [comment]
The problem is at 

```
resp, err := ec2Ref.CreateVolume(options)
```

When volumes are being created, it seems something changed on the API

**Comment by katcipis** [comment]
Actually, it is not the API, for some kind of reason the available zone is an empty string.

**Comment by katcipis** [comment]
Fixed by adding **availablezone: us-west-2a** to the volumes descriptor. This was not necessary before, Im going to update the examples and the docs for this.

**Comment by guilherme-santos** [comment]
I think I added a bug, because available zone of volumes should always be the same as instance zone... I'll review my last commits to try identify where is the problem.

**Comment by katcipis** [comment]
I see, so in the end I should not need to add the zone. For now Im using this to keep working :-)

It is time to have releases and tags on this project, this break caused me some trouble, I could just be using a stable release instead of the master.

**Comment by guilherme-santos** [comment]
Sure, you're right. I'm sorry about the problems that I caused.. After fix this bug I'll create the tag

**Comment by katcipis** [comment]
No problem, cant do anything awesome without screwing up sometimes :-)

Sorry I didnt identified it properly as a bug, Im not very aware of what is happening on the project, just using it. If you need a hand to fix it, Ill be around
